### ISSUE TITLE
[Feature Request]: Support AZAPI Provider 2.0

### ISSUE THREAD

**Issue by jkroepke** [cloudeteer/terraform-azurerm-vm#38]
### Feature Description

azapi 2.0 provider has been released with introduces some breaking changes.

Ref: https://github.com/cloudeteer/terraform-azurerm-vm/pull/30

Biggest change to mention: no more json, no jsondecode is manatory.

### Use Case

Keep dependencies up2date

### Privacy Statement

- [x] I agree

### Code of Conduct

- [x] I agree to follow this repository's Code of Conduct

**Comment by rswrz** [comment]
👀 [Announcing AzAPI 2.0](https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azapi-2-0/ba-p/4275733)
