### ISSUE TITLE
Module is not findable in Terraform registry

### ISSUE THREAD

**Issue by rswrz** [cloudeteer/terraform-azurerm-vm#9]
https://registry.terraform.io/search/modules?q=cloudeteer

![image](https://github.com/user-attachments/assets/2c9b0274-a6c0-4c27-a22b-e02e87afb3be)

**Comment by neonwhiskers** [comment]
Wrote an E-Mail to: terraform-registry@hashicorp.com 
A HashiCorp Ticket was created. Waiting on reply.

**Comment by rswrz** [comment]
It took some time, but now we can be found 🥳 

![Image](https://github.com/user-attachments/assets/949720df-1718-4d69-aec3-a75b2ac18ad8)
